### ISSUE TITLE
Html and Text need to be in different ParameterSets

### ISSUE THREAD

**Issue by jschpp** [EvotecIT/Mailozaurr#1]
So I've looked over Mailozaurr (nice name btw :-) )
Thank you for working on this 👍 

I've stumbled about a minor issue so far
When using `Send-EmailMessage` and setting `Text` as well as `Html` text will be overwritten.
see: https://github.com/jstedfast/MimeKit/blob/master/MimeKit/BodyBuilder.cs#L129-L166

I'd put those parameters in different Parametersets to reflect that.

**Comment by PrzemyslawKlys** [comment]
That's weird. As far as I understand MimeKit.BodyBuilder you can set both and it's even preferred. 

```
    $BodyBuilder = [MimeKit.BodyBuilder]::new()
    if ($HTML) {
        $BodyBuilder.HtmlBody = $HTML
    }
    if ($Text) {
        $BodyBuilder.TextBody = $Text
    }
    if ($Attachment) {
        foreach ($A in $Attachment) {
            $null = $BodyBuilder.Attachments.Add($A)
        }
    }
    $Message.Body = $BodyBuilder.ToMessageBody()
```

**Comment by jschpp** [comment]
Well it seems I'm blind.
You are absolutely correct.
