### ISSUE TITLE
SmtpClient Not Connected when using Send-EmailMessage

### ISSUE THREAD

**Issue by pseudobacon** [EvotecIT/Mailozaurr#10]
Hi I'm getting this error when trying to use the Send-EmailMessage cmdlet

![image](https://user-images.githubusercontent.com/12183854/96668496-05a38200-13a7-11eb-949c-9dd99b3b3a4a.png)

When I use the same smtpserver address with Mailkit.Net.Smtp.SmtpClient the email will send without issue

**Comment by PrzemyslawKlys** [comment]
What parameters exactly are you using to send with one and to send with other?

**Comment by pseudobacon** [comment]
With Mailozaurr: Send-EmailMessage -From 'emailaddress' -To 'emailaddress' -Subject 'subject' -SmtpServer 'server' -Attachments "attachmentfilepath" 

With Mailkit:

$smtp = New-Object Mailkit.Net.Smtp.SmtpClient
$message = New-Object MimeKit.MimeMessage
$messageBodyBuilder = New-Object MimeKit.BodyBuilder

$message.From.Add("emailaddress")
$message.To.Add("emailaddress")
$message.Subject = 'subject'

$messageBodyBuilder.Attachments.Add("attachmentfilepath") | Out-Null
$message.Body = $messageBodyBuilder.ToMessageBody()

$smtp.Connect('server')
$smtp.Send($Message)
$smtp.Disconnect($true)
$smtp.Dispose()

**Comment by PrzemyslawKlys** [comment]
The difference is in a port most likely. The default that I've taken is 587. Otherwise, there's no port defined and I guess it uses 25, and that's what you're looking for assuming no login/pass.

**Comment by pseudobacon** [comment]
![image](https://user-images.githubusercontent.com/12183854/96966158-0ed45080-1559-11eb-94c1-eb1269008ba7.png)
Actually it does default to 587. If I put -Port 587 at the end it still fails

**Comment by PrzemyslawKlys** [comment]
i mean put 25 at the end ...

**Comment by pseudobacon** [comment]
Works now!

**Comment by PrzemyslawKlys** [comment]
I'll change behavior to use 25 instead of 587. And add tips on errors.
