### ISSUE TITLE
Send-EmailMessage OAuth2 Authentication never actually Performed

### ISSUE THREAD

**Issue by Viajaz** [EvotecIT/Mailozaurr#17]
OAuth2 authentication is never actually performed in `Send-EmailMessage` because it first checks if `$SmtpCredentials` is not null, which is it because it is never assigned when specifying `-OAuth2`

https://github.com/EvotecIT/Mailozaurr/blob/master/Public/Send-EmailMessage.ps1#L431
https://github.com/EvotecIT/Mailozaurr/blob/master/Public/Send-EmailMessage.ps1#L581

**Comment by PrzemyslawKlys** [comment]
It would seem I've forgot to add `$SmtpCredentials = $Credential` in the oAuth2
