### ISSUE TITLE
Pester Tests

### ISSUE THREAD

**Issue by Viajaz** [EvotecIT/Mailozaurr#18]
Please consider creating [Pester](https://github.com/pester/Pester) [tests](https://pester.dev/docs/usage/test-file-structure) for common uses of Cmdlets and Functions.
This would identify issues such as https://github.com/EvotecIT/Mailozaurr/issues/17 early on.

**Comment by PrzemyslawKlys** [comment]
Writing pester tests are great - feel free to contribute some. The main problem with it - you actually need a working SMTP server on the other end - which means I would have to create some test accounts on tenant and have it running automatically with encrypted credentials.
