### ISSUE TITLE
Move email to a different folder

### ISSUE THREAD

**Issue by hdsouza** [EvotecIT/Mailozaurr#22]
I need to use Powershell and move an email in my GMAIL INBOX to a different folder.
I am using the Powershell module Mailozaurr to connect to Gmail via IMAP. I am able to correctly login and read emails in my Inbox.
Here is my code:
`
$FromAddress = "A12345@gmail.com"
$Password = "MY_password"
$Client = Connect-IMAP -Server 'imap.gmail.com' -Password $Password -UserName $FromAddress -Port 993 -Options Auto

Get-IMAPFolder -Client $Client -Verbose
foreach ($Email in $client.Data.Inbox) 
	{
	if ($Email.from -notlike "*test*") {continue}
	$Email
	Break
	}`

At this stage I want to move $email to a new folder named "NewFolder". How do i achieve this?
Please help, Thanks

**Comment by PrzemyslawKlys** [comment]
Hi,

https://github.com/jstedfast/MailKit/issues/160 will probably help. 

Basically you would need to do

```powershell
$matchFolder = $Client.GetFolder("YourFolder")
if ($matchFolder) {
    $Client.Data.Inbox.MoveTo($Email, $matchFolder) 
}
```

More or less, pseudo code above without testing.

**Comment by hdsouza** [comment]
Thanks @PrzemyslawKlys . Unfortunately the $Client.GetFolder("YourFolder") fails.
Error: Method invocation failed because [System.Collections.Specialized.OrderedDictionary] does not contain a method named 'GetFolder'.

**Comment by PrzemyslawKlys** [comment]
$Client.Data.GetFolder maybe?

**Comment by hdsouza** [comment]
That worked But the moveto line failed.

$TestFolder = $Client.data.GetFolder("Test")
$Client.Data.Inbox.MoveTo($Email, $TestFolder)

Error is:
Cannot find an overload for "MoveTo" and the argument count: "2".

**Comment by PrzemyslawKlys** [comment]
Type `$Client.Data.Inbox.MoveTo` without any brackets. You will get an output what is expected by that command. Most likely it expects ID. Probably $Email.Id or something. You need to figure out what it wants, and what properties $email has that can be used for that.

**Comment by hdsouza** [comment]
$TestFolder = $Client.data.GetFolder("Test")
#I Believe i have specify the message count.. in this case 0
$Client.Data.Inbox.MoveTo(0, $TestFolder)

At this stage I get an error:
Exception calling "MoveTo" with "2" argument(s): "The folder is not currently open in read-write mode."
I know the inbox is open because If I run ($Client.data.Inbox).Isopen it returns TRUE, although I am not sure how to check if its Open in read-write mode
Do they want the destination folder to be open as well? From what I am reading, only one folder can be open at a time and destination is not needed to be open (https://stackoverflow.com/questions/69472843/mailkit-imap-client-inbox-moveto-the-folder-is-not-currently-open-in-read-write/69473004#69473004)

**Comment by hdsouza** [comment]
Is this something that will be implemented on the next version of the module?

**Comment by hdsouza** [comment]
I finally figured out why it was not working. Looking at the backend code for the module (https://www.powershellgallery.com/packages/Mailozaurr/0.0.16/Content/Mailozaurr.psm1), the Inbox is open in ReadOnly mode.
Hence one cannot move an email out.

The workaround is  closing the Inbox, then reopening in ReadWrite mode and moving the email
Hence this is what worked for me:

$I_Folder = $Client.data.Inbox
$TestFolder = $Client.data.GetFolder("Test")

[MailKit.FolderAccess] $FolderAccess = [MailKit.FolderAccess]::ReadWrite
$I_Folder.close()
$I_Folder.Open($FolderAccess)
$I_Folder.MoveTo(0, $TestFolder)

It would have been a lot easier if the backend code was set to ReadWrite instead or ReadOnly

**Comment by PrzemyslawKlys** [comment]
Well,

```powershell
function Get-IMAPFolder {
    [cmdletBinding()]
    param(
        [System.Collections.IDictionary] $Client,
        [MailKit.FolderAccess] $FolderAccess = [MailKit.FolderAccess]::ReadOnly
    )
```

The choice on how to open the folder is yours. `Get-ImapFolder -FolderAccess ReadWrite` should just work. It's to prevent accidental damage.

**Comment by hdsouza** [comment]
Yes Get-ImapFolder -FolderAccess ReadWrite worked. Thanks @PrzemyslawKlys
