### ISSUE TITLE
How to specify 'Encoding' when sending mail using '-graph'

### ISSUE THREAD

**Issue by oolejniczak** [EvotecIT/Mailozaurr#23]
The '-encoding' parameter does not exist 'Send-EmailMessage' with '-Graph'.
Why is that?
How can you send "proper" message with French characters such as éàç ?

**Comment by PrzemyslawKlys** [comment]
Oversight on my part. I'll fix it. Generally by default it should work without you having to specify encoding (utf8) by default. I was sure it's added, as i do graph calls a lot.

**Comment by oolejniczak** [comment]
thanks for your great work and quick answer
I confirm that if i send "éàç", i receive '���'

**Comment by PrzemyslawKlys** [comment]
It should be simple fix, but I'll probably fix it on sunday.
