### ISSUE TITLE
Could not load file or assembly 'System.Runtime.CompilerServices.Unsafe

### ISSUE THREAD

**Issue by buckyj** [EvotecIT/Mailozaurr#28]
Hello,

I have installed your toolkit. When I try to run connect-imap I get the following warning:

WARNING: Connect-IMAP - Unable to connect Exception calling "Connect" with "3" argument(s): "Could not load file or assembly 'System.Runtime.CompilerServices.Unsafe, Version=4.0.4.1, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified."

What should I do to make this work?

Thank you.
Jan

**Comment by PrzemyslawKlys** [comment]
If you're using PowerShell 5.1 make sure you have net framework 4.7.2+ installed.

**Comment by PrzemyslawKlys** [comment]
Was your issue fixed?

**Comment by PrzemyslawKlys** [comment]
I've installed clean Windows 2016 and was able to generate this error.
