### ISSUE TITLE
"Send-EmailMessage -Verbose" Throws Exception if -HTML is less than 10 Characters

### ISSUE THREAD

**Issue by andrew0wells** [EvotecIT/Mailozaurr#3]
To reproduce:

`Send-EmailMessage -From @{ Name = 'Wells, Andrew'; Email = '<from address>' } -To '<to address>' -Credential $Credential -HTML "TEST" -Subject 'Test ' -Graph -Verbose -Priority High`

The exception received was 

Exception calling "Substring" with "2" argument(s): "Index and length must refer to a location within the string.
Parameter name: length"
At C:\Program Files\WindowsPowerShell\Modules\Mailozaurr\0.0.7\Mailozaurr.psm1:317 char:13
             $Message.message.body.content = -join ($Message.message.b ...
             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
     FullyQualifiedErrorId : ArgumentOutOfRangeException

My assumption is that this is because that line uses Substring, without checking to see if the length is at least 10 characters long. 

Great work on this module, btw!

**Comment by PrzemyslawKlys** [comment]
Ye, I'm using this for verbose purpose to display content for debugging graph. Normally if the HTML content would be large it would make VSCode stuck flooding my screen. I'll fix it - thanks for reporting!

**Comment by PrzemyslawKlys** [comment]
Unless you want to give this a try? PR maybe?

**Comment by andrew0wells** [comment]
I can set up a pull request later this evening. Do you normally require
unit tests on your pull requests?

**Comment by PrzemyslawKlys** [comment]
Well it would be great, except i've not setup any tests for Send-EmailMessage yet. So you can skip it for now :-) I need to write tests and actually setup testing in Azure for this with real emails being sent.

**Comment by PrzemyslawKlys** [comment]
Thank you
