### ISSUE TITLE
MX Record IPAddress with -Separate

### ISSUE THREAD

**Issue by MaKeG0** [EvotecIT/Mailozaurr#31]
Hello,
first of all thank you very much for you work, this tool is so powerful and I just started to scratch the surface.
It might be just my inexperience but when I use the `Find-MXRecord` with a single Domain as input and with only `-Separate` as parameter, the moment i pipe it to `Export-Csv` the IPAddress get always as `System.Object[].` 
I tried to add in the pipe many ways to `-join` the arrays of IPAddresses but I get always a Lenght column with some number values like 260. 
I tried to find the part in your source code where you wrote about the `-Separate` but I can't get my head around it.
There is somebody that can help me? I just need to put the IPAddresses in the csv with the `-Separate` but joined.
Also, as I'm already in topic, there is somebody that applied `-Separate` but with other `-Find`?
Thanks again and sorry for the dumb question.

**Comment by PrzemyslawKlys** [comment]
Why would you need -Separate if you can skip it and export to csv without it. 

```powershell
Find-MXRecord -DomainName evotec.pl | ConvertTo-Csv
```

```
Name        : evotec.pl
Count       : 1
Preference  : 10
TimeToLive  : 274
MX          : evotec-pl.mail.protection.outlook.com
IPAddress   : 104.47.51.138; 104.47.9.36
QueryServer : 192.168.240.189:53
```


```
"Name","Count","Preference","TimeToLive","MX","IPAddress","QueryServer"
"evotec.pl","1","10","208","evotec-pl.mail.protection.outlook.com","104.47.51.138; 104.47.9.36","192.168.240.189:53"
```

**Comment by MaKeG0** [comment]
In my case scenario I'm importing a csv with a list of domains scrolling it with a for each and most of the results were giving a Count of 2 or more. Because I'll need to import the resulting CSV into a Database I needed to isolate the MX results.
My next step would be to understand how the IPAddresses get into the Find-MXRecord so that for each different MX relative to the domain I'll be able to fill the it's relative IPAddress. 
With my last attempt each domain have multiple raws where each one have a different MX result but a joined list of the IPAdresses of the entire domain.

I managed to do a similar thing with the DKIM records removing the -join that there was in the DKIM field from the module script and running it into a similar loop like the one I wrote before. In this way when a domain is giving multiple DKIM count I can isolate a ROW for each result.

Luckly the other Find are giving only 1 or 0 results for each domain.

**Comment by PrzemyslawKlys** [comment]
What you could also use:

```
Find-MXRecord -DomainName evotec.pl -Separate | ConvertTo-FlatObject |   ConvertTo-Csv 

```

```  
"Name","Preference","TimeToLive","MX","QueryServer.Address","QueryServer.Port","QueryServer.AddressFamily.value__","QueryServer.SupportedUdpPayloadSize","QueryServer.DnsSuffix","IPAddress.1","IPAddress.2"
"evotec.pl","10","299","evotec-pl.mail.protection.outlook.com","192.168.240.192","53","2","4000","localdomain","104.47.8.36","104.47.9.36"
```

`ConvertTo-FlatObject` is part of PSSharedGoods.

**Comment by MaKeG0** [comment]
`Find-MXRecord -DomainName evotec.pl -Separate | ConvertTo-FlatObject |   ConvertTo-Csv `

It worked like a charm. Thank you very much. Now i will just need to work around the DKIM do manage the modified module.
