### ISSUE TITLE
SkipCertificateValidation => wrong naming

### ISSUE THREAD

**Issue by xroot16x** [EvotecIT/Mailozaurr#44]
https://github.com/EvotecIT/Mailozaurr/blob/cc806a2a2c9d6d2176ffb40872b5befbf997ac2a/Public/Send-EmailMessage.ps1#L78

The 'SkipCertificateValidation' parameter is $SkipCertificateValida**ta**tion, but the error message says :  "You can also try SkipCertificateValidation or SkipCertificateRevocation."

**Comment by PrzemyslawKlys** [comment]
It's a typo. I'll fix it, but we may need to add additional depracated parameter to tell people not to use it before removing to not introduce breaking change.

**Comment by xroot16x** [comment]
Thank you for the response ! ;-) 

----- Mail original -----

De: "Przemysław Kłys" ***@***.***> 
À: "EvotecIT/Mailozaurr" ***@***.***> 
Cc: "xroot16x" ***@***.***>, "Author" ***@***.***> 
Envoyé: Mardi 25 Juillet 2023 08:09:01 
Objet: Re: [EvotecIT/Mailozaurr] SkipCertificateValidation => wrong naming (Issue #44) 



It's a typo. I'll fix it, but we may need to add additional depracated parameter to tell people not to use it before removing to not introduce breaking change.
