### ISSUE TITLE
Logging

### ISSUE THREAD

**Issue by tes-com** [EvotecIT/Mailozaurr#46]
Hello,

Your Script is great save me a lot of time making it myself. 

I only have One Question. With Sending The mail there is a logging to screen. Is it posable for me to send it to a Steing so i can include it in my logfile ?

Thanks

Ronald

**Comment by PrzemyslawKlys** [comment]
By logging you mean diagnostics of SMTP? There is LogPath, LogConsole, LogObject, LogTimestamps and few other log commands. That's only for debugging tho. 

If you mean warning messages you can always save it WarningVariable VerboseVariable and then save to file on your own.

**Comment by tes-com** [comment]
Hello,

With Logging in mean that after the command Send-EmailMessage @sendEmailMessageSplat

The follwing will be displayed on the screen
[cid:8a7f6bc5-c6e1-4dca-afbc-47e147354548]

I Want this as a  Varible (or multiple variable) so i can include it im my Logfile that is generated by my script.

Thanks

Ronald
________________________________
Van: Przemysław Kłys ***@***.***>
Verzonden: woensdag 26 juli 2023 10:35
Aan: EvotecIT/Mailozaurr ***@***.***>
CC: Ronald J.P. Bok ***@***.***>; Author ***@***.***>
Onderwerp: Re: [EvotecIT/Mailozaurr] Logging (Issue #46)


By logging you mean diagnostics of SMTP? There is LogPath, LogConsole, LogObject, LogTimestamps and few other log commands. That's only for debugging tho.

If you mean warning messages you can always save it WarningVariable VerboseVariable and then save to file on your own.

**Comment by PrzemyslawKlys** [comment]
I don't see your screenshot. You need to provide it directly. Email won't work.

**Comment by tes-com** [comment]
Hello,

Hereby the Screenshot.
![image](https://github.com/EvotecIT/Mailozaurr/assets/16758637/4adf0fb5-8f99-40a3-9946-cd6088371ca3)

**Comment by PrzemyslawKlys** [comment]
$Variable = Send-EmailMessage
$Variable contains this data...
