### ISSUE TITLE
Cannot update Mailozaurr 1.0.2 - not trusted any longer

### ISSUE THREAD

**Issue by KlausObd** [EvotecIT/Mailozaurr#48]
Cannot update Mailozaurr 1.0.2 - not trusted any longer

 Update-Module "Mailozaurr"
Install-Package: Authenticode issuer 'CN=Przemysław Kłys EVOTEC, O=Przemysław Kłys EVOTEC, L=Mikołów, C=PL' of the new module
'Mailozaurr' with version '1.0.2' from root certificate authority 'CN=DigiCert Trusted Root G4, OU=www.digicert.com,
O=DigiCert Inc, C=US' is not matching with the authenticode issuer 'CN=Przemysław Kłys EVOTEC, O=Przemysław Kłys
EVOTEC, L=Katowice, S=Śląskie, C=PL' of the previously-installed module 'Mailozaurr' with version '1.0.0' from root
certificate authority 'CN=DigiCert Assured ID Root CA, OU=www.digicert.com, O=DigiCert Inc, C=US'. If you still want to
install or update, use -SkipPublisherCheck parameter.

mfg Klaus Oberdalhoff

**Comment by PrzemyslawKlys** [comment]
```
Install-Module Mailozaurr -Force -Verbose -SkipPublisherCheck
```

It's normal process when the certificate gets changed.

**Comment by KlausObd** [comment]
Thanks, 

sorry, didn't know this. - Of course it worked

mfg Klaus
