### ISSUE TITLE
-AttachSelf  option like in Emailimo

### ISSUE THREAD

**Issue by petercharleston** [EvotecIT/Mailozaurr#52]
Hi,

How to attach the DataTable as .html the same as -AttachSelf in Emailimo please ?

**Comment by PrzemyslawKlys** [comment]
THere's nothing like that. YOu need to generate HTML and just attach it using Attach parameter. The only way to get it would be to integrate ability to use Mailozaurr in PSWriteHTML/Emailimo which would allow that. That's something that I have plan for but not in nearest weeks unless someone want to do PR to PSWriteHTML project.
