### ISSUE TITLE
Assumed Path / Incorrect Path in Attachment Parameter (Linux)

### ISSUE THREAD

**Issue by nhjeffh** [EvotecIT/Mailozaurr#56]
Using latest stable version of Mailozaurr and PowerShell (Linux Installation)
Simple call:
Send-EMailMessage -To $t -From $from -Subject $subject -SmtpServer $server -UseSsl `
-Port 587 -Credentials $creds -Attachments $ar
The issue I am faced with is this:
$ar = "/tmp/myfile.txt" however, when running my simple script from /var/spool/scripts on my system, there is an assumed path for the attachments of "that" directory the script is being invoked from, and therefore the file is not found.

i.e Send-EMailMessage is attempting to attach: "/var/spool/scripts/myfile.txt" instead of "/tmp/myfile.txt"

How do I configure Mailozaurr to stop stripping path information from attachment filename string?

**Comment by PrzemyslawKlys** [comment]
The relevant code for this is here:

https://github.com/EvotecIT/Mailozaurr/blob/57b4159550349006f4e6081054fc879f7bd3e075/Public/Send-EmailMessage.ps1#L651-L655

I do no changes to the path itself so I have hard time understanding how either Mailozaurr or Mailkit would interfere with the linux path you provided. 

I don't see this being fault of either library or mailozaurr
