### ISSUE TITLE
Microsoft.Identity DLL conflicts with Microsoft Azure Authentication, PnP, ExchangeOnlineManagement and few other modules

### ISSUE THREAD

**Issue by RichardGardener** [EvotecIT/Mailozaurr#59]
Depending on the order the modules are loaded, connecting to msgraph `Connect-MsGraph` either works or fails.

Works;
Import-Module Microsoft.Graph.Authentication
import-module mailozaurr -RequiredVersion 1.0.4
connect-MgGraph @conGraphSplat
Welcome to Microsoft Graph!

fails;
import-module mailozaurr -RequiredVersion 1.0.4
Import-Module Microsoft.Graph.Authentication
connect-MgGraph @conGraphSplat

error:
connect-MgGraph : Could not load type 'Microsoft.Identity.Client.Extensions.Msal.MsalCachePersis
assembly 'Microsoft.Identity.Client, Version=4.61.3.0, Culture=neutral, PublicKeyToken=0a613f4dd
At line:1 char:1
connect-MgGraph @conGraphSplat
CategoryInfo          : NotSpecified: (:) [Connect-MgGraph], TypeLoadException
FullyQualifiedErrorId : Microsoft.Graph.PowerShell.Authentication.Cmdlets.ConnectMgGraph

Microsoft.Graph.Authentication version used 2.9.1

The order didn't matter for mailozaurr version 1.0.2.

Changing the order has resolved the problem, but thought you might like to know.

**Comment by PrzemyslawKlys** [comment]
This is described partially in:
- https://github.com/EvotecIT/Mailozaurr/issues/58

It's related to the version of Microsoft.Identity and version of PowerShell => if they match => should be no problems 

Please provide more information, especially the output of:

```powershell
$Folder = $Env:PSModulePath -split ";"
$Output1 = foreach ($F in $Folder) {
    if (Test-Path -Path $F) {
        Get-ChildItem -LiteralPath $F -Recurse -Filter "*.dll" | ForEach-Object {
            if ($_.Name -like "Microsoft.IdentityModel.Abstractions.dll") {
                [PSCustomObject] @{
                    Name    = $_.FullName
                    Version = $_.VersionInfo.FileVersion
                }
            }
        }
    }
}
$Output1 | Format-Table -AutoSize

# Could not load type 'Microsoft.Identity.Client.Extensions.Msal.MsalCachePersistenceException
$Output2 = foreach ($F in $Folder) {
    if (Test-Path -Path $F) {
        Get-ChildItem -LiteralPath $F -Recurse -Filter "*.dll" | ForEach-Object {
            if ($_.Name -like "Microsoft.Identity.Client.*") {
                [PSCustomObject] @{
                    Name    = $_.FullName
                    Version = $_.VersionInfo.FileVersion
                }
            }
        }
    }
}
$Output2 | Format-Table -AutoSize
```

And 

```powershell
$PSVersionTable
```

Also does it behave the same in PS 5.1 and PS 7?

**Comment by RichardGardener** [comment]
Thank you for your quick response.

The error only happens in PS 5.1

WindowsPowerShell 5.1

Name                           Value
----                           -----
PSVersion                      5.1.14393.7513
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.7513
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

Output1
Name                                                                                                                                  Version
----                                                                                                                                  -------
C:\Users\myaccount\Documents\WindowsPowerShell\Modules\Mailozaurr\1.0.4\Lib\Core\Microsoft.IdentityModel.Abstractions.dll           6.35.0.41201
C:\Users\myaccount\Documents\WindowsPowerShell\Modules\Mailozaurr\1.0.4\Lib\Default\Microsoft.IdentityModel.Abstractions.dll        6.35.0.41201
C:\Program Files\WindowsPowerShell\Modules\Az.Accounts\2.15.0\lib\netstandard2.0\Microsoft.IdentityModel.Abstractions.dll             6.22.1.30825
C:\Program Files\WindowsPowerShell\Modules\Az.Accounts\3.0.2\lib\netstandard2.0\Microsoft.IdentityModel.Abstractions.dll              6.35.0.41201
C:\Program Files\WindowsPowerShell\Modules\Microsoft.Graph.Authentication\2.9.1\Dependencies\Microsoft.IdentityModel.Abstractions.dll 6.31.0.40607
C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules\Az.Accounts\2.15.0\lib\netstandard2.0\Microsoft.IdentityModel.Abstractions.dll     6.22.1.30825


Output2
Name                                                                                                                                               Version
----                                                                                                                                               -------
C:\Users\myaccount\Documents\WindowsPowerShell\Modules\Mailozaurr\1.0.4\Lib\Core\Microsoft.Identity.Client.dll                                   4.61.3.0
C:\Users\myaccount\Documents\WindowsPowerShell\Modules\Mailozaurr\1.0.4\Lib\Default\Microsoft.Identity.Client.dll                                4.61.3.0
C:\Program Files\WindowsPowerShell\Modules\Az.Accounts\2.15.0\lib\netcoreapp2.1\Microsoft.Identity.Client.dll                                      4.49.1.0
C:\Program Files\WindowsPowerShell\Modules\Az.Accounts\2.15.0\lib\netcoreapp3.1\Microsoft.Identity.Client.Extensions.Msal.dll                      2.23.0.0
C:\Program Files\WindowsPowerShell\Modules\Az.Accounts\2.15.0\lib\netfx\Microsoft.Identity.Client.dll                                              4.49.1.0
C:\Program Files\WindowsPowerShell\Modules\Az.Accounts\2.15.0\lib\netfx\Microsoft.Identity.Client.Extensions.Msal.dll                              2.23.0.0
C:\Program Files\WindowsPowerShell\Modules\Az.Accounts\2.15.0\lib\netstandard2.0\Microsoft.Identity.Client.Broker.dll                              4.49.1.0
C:\Program Files\WindowsPowerShell\Modules\Az.Accounts\2.15.0\lib\netstandard2.0\Microsoft.Identity.Client.NativeInterop.dll                       0.13.3.0
C:\Program Files\WindowsPowerShell\Modules\Az.Accounts\3.0.2\lib\netstandard2.0\Microsoft.Identity.Client.Broker.dll                               4.61.3.0
C:\Program Files\WindowsPowerShell\Modules\Az.Accounts\3.0.2\lib\netstandard2.0\Microsoft.Identity.Client.dll                                      4.61.3.0
C:\Program Files\WindowsPowerShell\Modules\Az.Accounts\3.0.2\lib\netstandard2.0\Microsoft.Identity.Client.Extensions.Msal.dll                      4.61.3.0
C:\Program Files\WindowsPowerShell\Modules\Az.Accounts\3.0.2\lib\netstandard2.0\Microsoft.Identity.Client.NativeInterop.dll                        0.16.2.0
C:\Program Files\WindowsPowerShell\Modules\Mailozaurr\1.0.2\Lib\Core\Microsoft.Identity.Client.dll                                                 4.44.0.0
C:\Program Files\WindowsPowerShell\Modules\Mailozaurr\1.0.2\Lib\Default\Microsoft.Identity.Client.dll                                              4.44.0.0
C:\Program Files\WindowsPowerShell\Modules\Microsoft.Graph.Authentication\2.9.1\Dependencies\Microsoft.Identity.Client.Broker.dll                  4.56.0.0
C:\Program Files\WindowsPowerShell\Modules\Microsoft.Graph.Authentication\2.9.1\Dependencies\Microsoft.Identity.Client.NativeInterop.dll           0.13.8.0
C:\Program Files\WindowsPowerShell\Modules\Microsoft.Graph.Authentication\2.9.1\Dependencies\Core\Microsoft.Identity.Client.dll                    4.56.0.0
C:\Program Files\WindowsPowerShell\Modules\Microsoft.Graph.Authentication\2.9.1\Dependencies\Core\Microsoft.Identity.Client.Extensions.Msal.dll    4.56.0.0
C:\Program Files\WindowsPowerShell\Modules\Microsoft.Graph.Authentication\2.9.1\Dependencies\Desktop\Microsoft.Identity.Client.dll                 4.56.0.0
C:\Program Files\WindowsPowerShell\Modules\Microsoft.Graph.Authentication\2.9.1\Dependencies\Desktop\Microsoft.Identity.Client.Extensions.Msal.dll 4.56.0.0
C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules\Az.Accounts\2.15.0\lib\netcoreapp2.1\Microsoft.Identity.Client.dll                              4.49.1.0
C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules\Az.Accounts\2.15.0\lib\netcoreapp3.1\Microsoft.Identity.Client.Extensions.Msal.dll              2.23.0.0
C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules\Az.Accounts\2.15.0\lib\netfx\Microsoft.Identity.Client.dll                                      4.49.1.0
C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules\Az.Accounts\2.15.0\lib\netfx\Microsoft.Identity.Client.Extensions.Msal.dll                      2.23.0.0
C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules\Az.Accounts\2.15.0\lib\netstandard2.0\Microsoft.Identity.Client.Broker.dll                      4.49.1.0
C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules\Az.Accounts\2.15.0\lib\netstandard2.0\Microsoft.Identity.Client.NativeInterop.dll               0.13.3.0
C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules\MSAL.PS\4.16.0.4\Microsoft.Identity.Client.4.16.0\net45\Microsoft.Identity.Client.dll           4.16.0.0
C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules\MSAL.PS\4.16.0.4\Microsoft.Identity.Client.4.16.0\netcoreapp2.1\Microsoft.Identity.Client.dll   4.16.0.0

PS 7.4.6 works if you load your module first.
Name                           Value
----                           -----
PSVersion                      7.4.6
PSEdition                      Core
GitCommitId                    7.4.6
OS                             Microsoft Windows 10.0.14393
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

**Comment by PrzemyslawKlys** [comment]
Isn't it a problem with Microsoft.Graph.Authentication being pretty old in your setup? 2.9.1 vs 2.25.0 currently? Which is why there's "identity.dll" conflict

**Comment by PrzemyslawKlys** [comment]
![image](https://github.com/user-attachments/assets/7992a416-6893-4afb-bac5-f57b2826fe52)

![image](https://github.com/user-attachments/assets/4302babb-cff5-47df-93cf-7275507744c8)

**Comment by PrzemyslawKlys** [comment]
In Mailozaurr 1.0.2:

- C:\Program Files\WindowsPowerShell\Modules\Mailozaurr\1.0.2\Lib\Core\Microsoft.Identity.Client.dll 4.44.0.0
- C:\Program Files\WindowsPowerShell\Modules\Mailozaurr\1.0.2\Lib\Default\Microsoft.Identity.Client.dll 4.44.0.0

In Microsoft.Graph.Authentication:
- C:\Program Files\WindowsPowerShell\Modules\Microsoft.Graph.Authentication\2.9.1\Dependencies\Desktop\Microsoft.Identity.Client.dll 4.56.0.0

The logic in Mailozaurr is that if you load it, and there's already Microsoft.Identity.Client loaded it will try to use that. This means Mailozaurr will ignore the version check if Authentication module is first loaded and use that. So any Identity.DLL should work  for it, be it 1.0.2 or 1.0.4. However in 1.0.4 there's 4.61.3 version, which is higher than required by Authenticator, which is why it fails

**Comment by RichardGardener** [comment]
Checking Microsoft.Graph.Authentication, the latest version is 2.25.0, which has the same Identity.DLL version as Mailozaurr, 4.61.3.

I'll need to look at upgrading the version of msgraph that we are using in production.

Thank you for your help.
