### ISSUE TITLE
Change NET Framework + Net Core to Net Standard to mnimize library size

### ISSUE THREAD

**Issue by user8446** [EvotecIT/Mailozaurr#7]
Not a bug but maybe a suggestion to maybe use MimeKitLite instead of MimeKit for the dll. It's approx. 24% smaller making the loading quicker and everything more lightweight. I switched to that in your module and everything is working fine. 
The only difference between the two is the crypto is not in the lite version (s/mime stuff, etc.)
Thank you for the module, it's expertly written!

**Comment by PrzemyslawKlys** [comment]
S/MIME is most likely coming. I spoke with @FredWeinmann who said he wanted to PR this functionality. Not sure if it's gonna be 1 week, 1 month, or 6 months but a 24% difference is not big. 

What I can try to do is change Default/Core libraries into Standard one. I did for https://github.com/EvotecIT/MarkdownPrince and it works fine, it's just matter of testing and making sure all those libs have proper Standard version. This will mean the size of module will go down 2x.

**Comment by user8446** [comment]
Understood... I wasn't aware of the upcoming crypto additions to the module.
Thank you!

**Comment by PrzemyslawKlys** [comment]
Due to some library conflicts this needs to stay Default/Core.
